services:
  frontend:
    build: ./src/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./src/backend/API
    ports:
      - "5000:5000"
    depends_on:
      - db
      - ml

  ml:
    build: ./src/ml
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stockpredictor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
